name: CI Pipeline for HNG FastAPI 

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout Code
    
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.2"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv venv
        source venv/bin/activate
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Test with pytest
      run: |
        source venv/bin/activate
        pytest
        
  
